# Generated by Django 5.0.6 on 2024-06-29 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                ("id_ingrediente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_ingrediente", models.CharField(max_length=100)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unidad", models.CharField(max_length=10)),
                ("estado_ingrediente", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id_rol", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_rol", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True)),
                ("estado", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=50)),
                ("contraseña_usuario", models.CharField(max_length=20)),
                (
                    "rol_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.rol"
                    ),
                ),
            ],
        ),
    ]
