# Generated by Django 5.0.4 on 2024-06-24 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('rol_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rol')),
            ],
        ),
    ]
