# Generated by Django 5.0.6 on 2024-07-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_precioproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precioproducto',
            old_name='precio_ingrediente',
            new_name='precio_producto',
        ),
        migrations.RemoveField(
            model_name='precioproducto',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='precioproducto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
            preserve_default=False,
        ),
    ]
