# Generated by Django 5.0.6 on 2024-07-27 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_precio_ingrediente_precioproducto_precio_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioproducto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
    ]
