# Generated by Django 5.0.6 on 2024-07-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_precioingrediente_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductoIngrediente',
        ),
    ]
