# Generated by Django 5.0.6 on 2024-07-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_producto_ingredientes_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado_producto',
        ),
    ]
