# Generated by Django 5.0.6 on 2024-07-28 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_productoingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoingrediente',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.unidadesmedida'),
            preserve_default=False,
        ),
    ]
