# Generated by Django 5.0.6 on 2024-07-28 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_productoingrediente_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioingrediente',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.unidadesmedida'),
        ),
    ]
