# Generated by Django 5.0.7 on 2024-07-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_costoproducto_costoproductoingrediente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precioproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='precio_ingrediente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_producto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='PrecioIngrediente',
        ),
        migrations.DeleteModel(
            name='PrecioProducto',
        ),
    ]
