# Generated by Django 5.0.4 on 2024-08-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_costoproductoingrediente_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingredientes',
        ),
        migrations.AlterField(
            model_name='receta',
            name='producto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='ingrediente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='unidad',
            field=models.CharField(max_length=50),
        ),
    ]
