# Generated by Django 5.0.7 on 2024-08-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_receta_ingredientes_alter_receta_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganancia',
            fields=[
                ('id_ganancia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('costo_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_con_ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_producto',
        ),
    ]
