# Generated by Django 5.0.7 on 2024-08-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_cliente_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
